### ISSUE TITLE
[SCIM] can create a user with a corrupted email property

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#376]
Hello :)

When creating a user without an email, then doing the following PATCH operations, the attributes in the DB do not have a value for `parent_attribute_id`.

To reproduce:
1. POST a user 
```
{"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"externalId":"78a07f0c-c4b9-47da-8cff-fd1fc5391dfc","userName":"test@test.com","active":true,"displayName":"Test Test","meta":{"resourceType":"User"},"name":{"formatted":"Test Test","familyName":"Test","givenName":"Test"}}
```
2. PATCH the created user
```
{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"Add","path":"emails[type eq "work"].primary","value":"true"},{"op":"Add","path":"emails[type eq "work"].type","value":"work"}]}
```

Now the`parent_attribute_id` values will be null, and there won't be an attribute with `emails` full path.

3. PATCH again
```
{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"Add","path":"emails[type eq \"work\"].value","value":"test@test.com"},{"op":"Add","path":"emails[type eq "work"].primary","value":"true"},{"op":"Add","path":"emails[type eq "work"].type","value":"work"}]}
```

Now when you GET this user, you'll see its email and other attributes as top level keys in the returned representation.

Do you know why is this happening?

Kind regards
Dan

**Comment by danflomin** [comment]
Hi,
Is this also released in 2.0.24-ci-00381 ?
I reproduces on this version as well.

Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello,

In the previous implementation, there was an issue when an HTTP PATCH request with `add` operation was executed to update a complex path for example : `emails[type eq 'work'].primary`. Instead of updating the existing children, new ones were added into the collection.

I tried to reproduce your bug on my local machine but I cannot reproduce it :(.
In the second operation you're trying to patch properties which don't exist in the initial representation (path : `emails[type eq "work"].primary `).

Can-you please use this nuget package `SimpleIdServer.Scim --version 2.0.24-ci-00384`

HTTP POST Add : the `emails` property is missing.
```
{
	"schemas": ["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],
	"externalId":"78a07f0c-c4b9-47da-8cff-fd1fc5391dfc",
	"userName":"test2@test.com",
	"active":true,
	"displayName":"Test Test",
	"name": {
		"formatted":"Test Test",
		"familyName":"Test",
		"givenName":"Test"
	},
	**"emails": [
		{
			"type": "work",
			"value": "email@email.com"
		}	
	]**
}
```

KR,

SID

**Comment by danflomin** [comment]
Hello 

An integral part of this issue is that the initial POST request does not have an email in its body.
I saw it happens when services initially do not have an email for a user, but later add it.

I was thinking that if the initial body has no email property, and later a PATCH requests tries to add one, then it should also create the parent attribute.

What do you think?


Kind regards
Dan

**Comment by simpleidserver** [comment]
The issue should be fixed in this version:

```
dotnet add package SimpleIdServer.Scim --version 2.0.24-ci-00386 --source https://www.myget.org/F/advance-ict/api/v3/index.json
```

**Comment by danflomin** [comment]
I checked it out, and it looks partially solved.

Now I get 2 emails in the array after first PATCH request (should be just one)

```
    "emails": [
        {
            "type": "work",
            "primary": true
        },
        {
            "type": "work"
        }
    ]
```

The second PATCH works even more strangely (I get many emails):

```
    "emails": [
        {
            "type": "work",
            "primary": true
        },
        {
            "type": "work"
        },
        {
            "value": "test@test.com",
            "type": "'work'"
        },
        {
            "type": "work"
        },
        {
            "primary": true,
            "type": "'work'"
        }
    ],
```

**Comment by danflomin** [comment]
It looks like this is fixed in `2.0.24-ci-00388` !

Thanks !

**Comment by danflomin** [comment]
Is this covered with UTs on your end?

**Comment by simpleidserver** [comment]
Yes it is covered with UTs
