### ISSUE TITLE
How can I get the roles associated with a user?

### ISSUE THREAD

**Issue by lechediaz** [simpleidserver/SimpleIdServer#525]
Hello friend,

I have created a role in my client, added it to a group and then associated it to a user, but I can't get the role.

I created a scope of type Identity Resource and added it to my client, but it does not work neither in singular or plural.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/390bc47f-cbd6-4ffb-9d44-29846909e7d5)

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/87550b9e-b025-4d72-9fc5-49ed677bbbff)

In the `access_token` it doesn't come, so I supposed I could look it up in the `userinfo_endpoint` but it doesn't come up either.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/b2b5e710-601e-45b4-a915-0113cd4eeed2)

In the discovery enpoint there is no endpoint where to get this data.

**Comment by lechediaz** [comment]
I tried to save the scopes as API Resource type and it didn't work either.

**Comment by lechediaz** [comment]
I can see that in the UserInfo controller it brings information about the associated groups of a user but does nothing with it.

In the references you can see that it is not used in some logic to create claims.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/4a62ebd3-5e4d-413e-babb-3cca0a7c6bde)

I think that if the "role" scope is requested it should bring the roles in a claim called "role" where this information will come when the User Info ednpoint is requested.

Initially I thought that the "role" claim was not created on the user when associating the group, but if it is, then only this information needs to be retrieved.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/1a06e981-2f4a-4d19-8a1c-1fb04effb131)

in fact I don't know why the record appears twice.

**Comment by lechediaz** [comment]
I found that in the UserInfo controller there is a call to the `ClaimsExtractor.ExtractClaims` method and I think the problem is in getting the FullPath of the group, because it is splitting by dot "." instead of slash "/".

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/d28556a1-22ab-438f-87e6-200dc780a584)

Tomorrow I will try to validate, if I find anything and let you know.

**Comment by simpleidserver** [comment]
The issue about duplicate roles have been fixed (Ticket #526).

Fetch the latest changes from the branch `origin/master` and remove all the roles of the user.
In the `role` scope, add a mapping rule. 
Click on the `Add mapper` button.  In the popup window, select `Attribute` and click on next :

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10213388/95c0aa43-181b-40c8-92bd-82edbcedc891)

Complete the form like this and click on `Save` : 

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10213388/69b6668f-9608-4032-815e-0cdf86faaea9)

Now, the `role` scope should be configured.

**Comment by lechediaz** [comment]
Okay friend, I'll try it and let you know.

**Comment by lechediaz** [comment]
Hello,

Aafter I got the changes and did what you told me to do, I assigned the group (with the previously associated role) to the user:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/f0956995-fb1a-4287-a3ca-fdca150b59e4)

Then checked the `Resolve roles` box and saved:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/9c5974f6-675d-4274-ac19-59a1d9701fc9)

Now, the UserInfo endpoint already brings me the role! :D but it does it twice

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/01dd0498-d74f-4ff0-b245-70a365274cfc)

Then what I did was deleted the "role" claim at user:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/be4928da-4923-455b-aa65-38f0f88bb2fb)

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/f10fc52d-c680-4052-9f02-59297f1bbee6)

Then when `access_token` is created, apparently creates the claim again, maybe that is what produces twice "role" key in UserInfo endpoint.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/b81130ba-f0bf-42b3-a877-2a4ecd2c46bf)

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/2f87aefa-3db6-40c6-b8e5-f4bd6684b4aa)

Still, it was a breakthrough and I could continue working on my project.

Thank you very much

**Comment by simpleidserver** [comment]
First thank you for your feedback :)
Roles are duplicated when you're trying to get an access token because the EF Change Tracker Detects changes on the user and save the result.

The issue is fixed in the `master` branch & it is linked to this problem #526.

Can-you please fetch the latest changes made on the master branch ?

**Comment by lechediaz** [comment]
OK, I'll try it and let you know.

**Comment by lechediaz** [comment]
Hello,

Okay, I got the changes but unfortunately the problem persists.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/35067a06-cb92-4ef6-8b6d-f0aab6f6c5f0)

Then I deleted my user's claims:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/4f168dfc-d7f3-46fe-95ee-296fe0f4f13e)

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/72bc19a3-e35a-4a1e-8c18-a5e793cc074f)

Then, I requested a new token and called the UserInfo endpoint and the role appears twice:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/cd3cf884-747e-4e68-9f9e-19b3d3ad1c9d)

I checked and indeed re-created the Claim to the user.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/cc621982-8ac2-4f1f-a7af-90b671566a97)

If I request another token it creates another claim and a third role in the UserInfo:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/47c2c982-77ce-46c8-a1bf-fd146591b60d)

**Comment by simpleidserver** [comment]
Strange, with the latest changes, the issue cannot be reproduced on my local machine.
Did-you rebuild the Docker Image and deploy the latest version to your Server ?
When auth code is used to get an access token and the userinfo is called, there is no duplicate role in the [dbo].[UserClaims] table.

**Comment by lechediaz** [comment]
mmm I'll check it again.

**Comment by lechediaz** [comment]
Oh, I'm so sorry, you were right I missed to load the correct image.tar file. It's working good.

I also noticed that it is not necessary to check the `Resolve roles` checkbox, with the attribute mapping it is enough and that is great (I don't know if the functionality of this checkbox is deprecated then).

![image](https://github.com/simpleidserver/SimpleIdServer/assets/8315469/5ede69f3-6503-40ec-b40e-c71f2eb1825a)

Thank you!
